branches:
  main:
    regex: ^main$
    increment: None
    is-mainline: true
    tracks-release-branches: false
    tag: ''
    source-branches: ['release', 'hotfix']

  develop:
    regex: ^dev(elop)?(ment)?$
    mode: ContinuousDelivery
    increment: Minor
    tag: ''
    is-mainline: true
    tracks-release-branches: true
    source-branches: ['main', 'release', 'feature', 'hotfix']

  release:
    regex: ^release[/-]
    increment: Major
    tag: "beta"
    prevent-increment-of-merged-branch-version: true
    track-merge-target: true
    tracks-release-branches: false
    is-release-branch: true
    source-branches: ['develop', 'release']

  hotfix:
    regex: ^hotfix[/-]
    increment: Patch
    tag: ''
    track-merge-target: true
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    source-branches: ['main']

  feature:
    regex: ^features?[/-]
    increment: Inherit
    tag: useBranchName
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    tracks-release-branches: true
    is-release-branch: false
    source-branches: ['develop', 'feature']

  pull-request:
    regex: ^(pull|pull\-requests|pr)[/-]
    mode: ContinuousDeployment
    tag: "PullRequest"
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    track-merge-target: false
    source-branches: ['develop', 'main', 'release', 'feature', 'hotfix']

no-bump-message: "^Merge branch '(dev|develop|main)(ment)?' into release"

ignore:
  sha: []
merge-message-formats: {}
